---
# Playbook to Verify that the required CAPO Images for a Deployment are present.
# Check is performed against the Deployments OpenStack Tenancy.
# If Images not Present:
# Playbook attempts to locate Images on Build Server & Uploads to OpenStack.
# If Images already Present:
# No action taken & Playbook Completes Successfully
#
# Required Vars:
# - deployment_id = String - Example ( ccd-c10a001 )
#
# Optional Vars:
# - search_image_dir
#     > String - Path to Images Location
#     > Default - /ccd/IMAGES
#     > Example Override - /ccd/IMAGES/STAGING
#
# Example usage
# -------------
# Manually enter ansible vault passwd:
# $ ansible-playbook check-and-upload-images.yml -e deployment_id=<deployment_id> --ask-vault-pass [ -e search_image_dir=/path/to/dir ]
#
# Retrieve ansible vault passwd from file:
# $ ansible-playbook check-and-upload-images.yml -e deployment_id=<deployment_id> --vault-password-file /path/to/file [ -e search_image_dir=/path/to/dir ]
#
- hosts: localhost
  gather_facts: no
  vars:
    dit_url: http://atvdit.athtem.eei.ericsson.se
    ip_version: "not defined"
    dit_url: http://atvdit.athtem.eei.ericsson.se
    sftp_host: "sftp.sero.ict.ericsson.net" 
    ansible_python_interpreter: "{{ ansible_playbook_python }}"

  tasks:
    - name: Download Deployment /tmp/ansible-facts-{{ deployment_id }}.json from sftp 
      command: >
        lftp -d -u {{ sftp_user }},{{ sftp_password }} -e 'set sftp:connect-program "ssh -o StrictHostKeyChecking=no";set ftp:proxy; get ccd_pipeline/deployments/ansible-facts-{{ deployment_id }}.json -o /tmp/ansible-facts-{{ deployment_id }}.json; exit' sftp://{{ sftp_host }}
      register: sftp_result
      ignore_errors: yes
    
    - name: Parse JSON content
      set_fact:
        deployment_data: "{{ lookup('file', '/tmp/ansible-facts-' ~ deployment_id ~ '.json') | from_json }}"

    - name: Display the variable
      debug:
        var: deployment_data

    ## Register ccd version into variable.
    - name: Get ccd version
      set_fact:
        ccd_version: "{{ deployment_data.dtt_deployment.products | json_query(products_qry) | first | json_query(config_qry) | first }}"
      vars:
        products_qry: "[? product_type_name == 'CCD'].configuration"
        config_qry: "[? key_name == 'version'].key_value"

    - name: Download openstack credentials from MinIO XDN
      include_role:
        name: creds_xdn
      vars:
        name: openstack_access_vars
        file: openstack_creds.yml

    - name: Set openstack username and password vars from openstack creds var
      no_log: yes
      set_fact:
        openstack_user: "{{ openstack_access_vars.openstack_user }}"
        openstack_password: "{{ openstack_access_vars.openstack_password }}"

    - name: "Check cloud for existing version {{ ccd_version }} images"
      os_image_info:
        verify: no 
        auth:
          auth_url: "{{ deployment_data.dit_pod.authUrl }}"
          username: "{{ openstack_user }}"
          password: "{{ openstack_password }}"
          project_name: stsccdpipeline
          project_domain_name: Default
          user_domain_name: Default
        image: "eccd-capo-{{ ccd_version }}-{{ item }}"
      register: result
      with_items:
        - "ephemeral"
        - "node"

    - name: Upload images to OpenStack cloud
      when: result.results[0].images == [] or result.results[1].images == []
      block:
        - name: Get the CAPO image directory for {{ ccd_version }} on local
          find:
            paths: "{{ capo_image_path }}"
            file_type: directory
            use_regex: yes
            patterns: ".*{{ ccd_version }}.*"
          register: image_dir

        - name: SFTP SYNC
          when: image_dir.files == []
          block:
            - name: Check image on SFTP
              command:  >
                lftp -u {{ sftp_user }},{{ sftp_password }} -e 
                'set sftp:connect-program "ssh -o StrictHostKeyChecking=no";
                set ftp:proxy ;
                ls ccd_pipeline/images;exit'
                sftp://{{ sftp_host }}
              register: sftp_result_images

            - name: Find file with {{ ccd_version }} tgz file
              ansible.builtin.set_fact:
                found_file_name: "{{ item.split()[-1] }}"
              loop: "{{ sftp_result_images.stdout_lines }}"
              when: ccd_version in item
              register: file_names_found
            
            - name: Ensure local download directory exists
              file:
                path: "/tmp/images"
                state: directory

            - name: download images tgz  from XDN SFTP
              command:  >
                lftp -u {{ sftp_user }},{{ sftp_password }} -e 
                'set sftp:connect-program "ssh -o StrictHostKeyChecking=no";
                set ftp:proxy ;
                pget ccd_pipeline/images/{{ found_file_name }} -o /tmp/images/{{ found_file_name }};exit'
                sftp://{{ sftp_host }}
              register: sftp_result_dload

            - name: Display results of SFTP download
              debug:
                var: sftp_result_dload

            - name : Unpack images
              command: "/bin/bash -c 'cd /tmp/images && for item in $(ls | grep tgz); do tar xvfz $item -C {{ capo_image_path }}; done'"


        - name: Find local images
          include_role:
            name: capo_getimage_path

        - name: Find CAPO {{ ccd_version }} image paths
          find:
            paths: "{{ ccdadm_dir }}"
            file_type: file
            use_regex: yes
            recurse: yes
            patterns: 
              - '{{ item }}.*\.img$'
          register: images
          with_items:
            - "ephemeral"
            - "node"

        - name: Fail if image files not found
          fail:
            msg: Cound not CAPO image files for CAPO version {{ ccd_version }}
          when: images.results[0].files[0].path | length <= 0 or images.results[1].files[0].path | length <= 0

        - name: Upload ephemeral and node images
          os_image:
            verify: no 
            auth:
              auth_url: "{{ deployment_data.dit_pod.authUrl }}"
              username: "{{ openstack_user }}"
              password: "{{ openstack_password }}"
              project_name: stsccdpipeline
              project_domain_name: Default
              user_domain_name: Default
            name: "{{ item.name }}"
            container_format: bare
            disk_format: raw
            state: present
            filename: "{{ item.file }}"
            is_public: true
            properties:
              cpu_arch: x86_64
              distro: ubuntu
          loop:
            - name: "eccd-capo-{{ ccd_version }}-ephemeral"
              file: "{{ images.results[0].files[0].path | string | regex_search('.*ephemeral.*') }}"
            - name: "eccd-capo-{{ ccd_version }}-node"
              file: "{{ images.results[1].files[0].path | string | regex_search('.*node.*') }}"
