- name: Check the current govc version (if any)
  command: "{{ govc_path }}/govc version"
  ignore_errors: true
  register: govc_version_found
  changed_when: false

- block:
  - name: Download the govc binary
    get_url:
      url: "{{ govc_download_url }}/govc_linux_amd64.gz"
      dest: "{{ govc_path }}/govc-{{ govc_version }}.gz"
      validate_certs: false
      mode: 0666

  - name: Uncompress the govc binary
    command: "gunzip {{ govc_path }}/govc-{{ govc_version }}.gz"
    args:
      creates: "{{ govc_path }}/govc-{{ govc_version }}"

  - name: Rename {{ govc_path }}/govc-{{ govc_version }} to {{ govc_file }}
    command: mv "{{ govc_path }}/govc-{{ govc_version }}" "{{ govc_file }}"

  - name: Set {{ govc_file }} as executable
    file:
      path: "{{ govc_file }}"
      mode: 0755

  when: |
    ( govc_version_found is defined and govc_version_found is failed )
    or ( govc_version_found.stdout is defined and govc_version not in govc_version_found.stdout )

- name: Verify installed govc version
  command: "{{ govc_path }}/govc version"
  ignore_errors: false
  register: govc_version_installed
  changed_when: false

- name: Assert correct installed version ({{ govc_version }})
  assert:
    that: "govc_version_installed is not failed and govc_version_installed.stdout is defined and govc_version in govc_version_installed.stdout"
  when: not ansible_check_mode