---
- name: Check if Security Group Already Exists on OpenStack
  command: openstack security group show {{ security_group_name }}
  register: security_search_results
  delegate_to: "{{ build_server_ip }}"
  failed_when: security_search_results.rc not in (0,1)
  environment:
    OS_AUTH_URL: "{{ cloud_auth.auth_url }}"
    OS_PROJECT_ID: "{{ cloud_auth.project_id }}"
    OS_USER_DOMAIN_NAME: "{{ cloud_auth.user_domain_name }}"
    OS_USERNAME: "{{ cloud_auth.username }}"
    OS_PASSWORD: "{{ cloud_auth.password }}"

- name: Block For Creating Security Group & Rule if it Doesnt Already Exist
  when:
    - security_search_results.stdout_lines | length == 0
    - "'No SecurityGroup found' in security_search_results.stderr"
  block:
    - name: Ensure Security Group is Created on OpenStack
      os_security_group:
        auth: "{{ cloud_auth }}"
        state: present
        name: "{{ security_group_name }}"
        description: Security group for "{{ security_group_name }}"
      register: security_results

    - name: Set the Security Group Result
      set_fact:
        osk_security_group_results: "{{ security_results.secgroup }}"

    - name: Create Security Group Rule
      os_security_group_rule:
        auth: "{{ cloud_auth }}"
        state: present
        security_group: "{{ security_group_name }}"
        direction: ingress
        protocol: "{{ protocol }}"
      register: security_group_rule_result
      vars:
        protocol: null # Protocol 'ANY' not available in module, null produces the same result

    - name: Set the Security Group Rule Result
      set_fact:
        osk_security_group_rule_results: "{{ security_group_rule_result.rule }}"
