---
- name: Delete Volume from OpenStack
  os_volume:
    auth: "{{ cloud_auth }}"
    state: absent
    display_name: "{{ volume_name }}"
  register: volume_results

- name: Set the Volume Delete Result
  set_fact:
    osk_delete_volume_results: "{{ volume_results }}"