---
- import_playbook: get-prod-promtheus-ip.yml
- name: Delete CCD target to prometheus
  hosts: prometheus
  vars_files: vars/group_vars/prometheus.yml
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ccd_url: "{{ url_prefix }}.{{ deployment_id }}.{{ url_domain }}"

  tasks:
    - name: Verify deployment_id is defined
      fail: msg="The required variable 'deployment_id' is not defined or null"
      when:
        - ( deployment_id is not defined ) or ( deployment_id|length == 0 )

    - name: Get a list of existing active targets from prometheus API
      uri:
        url: http://{{ ansible_default_ipv4.address }}:9090/api/v1/targets
        method: GET
        return_content: yes
        status_code: 200
        body_format: json
      register: result
      retries: 1
      delay: 1

    - name: Store list of current active targets in fact activeTargets
      set_fact: activeTargets={{ result | json_query('json.data.activeTargets[].discoveredLabels.__address__') }}

    - name: set fact "ccd_added" to yes if "{{ ccd_url }} is in  fact activeTargets
      set_fact:
        ccd_active: yes
      when: ccd_url  in  activeTargets

    - name: set fact "ccd_added" to no if {{ ccd_url }} is in fact activeTargets
      set_fact:
        ccd_active: no
      when: "ccd_url  not in  activeTargets"

    - name: Print debug to show if the {{ ccd_url }} already in activeTargets
      debug:
        msg: "CCD already in prometheus ?  {{ ccd_active | string }} "

    - name: Remove ccd prometheus URL from ccd-list.conf file
      lineinfile:
        path: /etc/prometheus/{{ ccd_list_file }}
        regex: '^.*"{{ url_prefix }}.{{ deployment_id }}.{{ url_domain }}".*$'
        state: absent
      register: target_remove_result
      when: ccd_active

    - name: Print debug message when {{ ccd_list_file }} has been updated
      debug:
        msg: "Changed = {{ target_remove_result.changed }} , {{ target_remove_result.msg }}  from /etc/prometheus/{{ ccd_list_file }}"
      when: ccd_active

    - name: sleep for 5 seconds to allow file_sd in prometheus to pick up change to {{ ccd_list_file }}
      wait_for:
        timeout: 5
      when: ccd_active

    - name: Check if ccd  target has been added to  in prometheus active targets
      uri:
        url: "http://{{ ansible_default_ipv4.address }}:9090/api/v1/targets"
        method: GET
        return_content: yes
        status_code: 200
        body_format: json
      register: result
      retries: 1
      delay: 1

    - name: Capture list of current active targets  in fact activeTargets
      set_fact: activeTargets={{ result | json_query('json.data.activeTargets[].discoveredLabels.__address__')  }}

    - name: set fact "ccd_active" to no if {{ ccd_url }} is in  fact activeTargets
      set_fact:
        ccd_active: no
      when: " ccd_url  not in  activeTargets "

    - name: set fact "ccd_active" to no  if {{ ccd_url }} is in  fact activeTargets
      set_fact:
        ccd_active: yes
      when: " ccd_url  in  activeTargets "

    - debug:
        msg: "Is the CCD target {{ ccd_url }} in the activeTarget?  {{ ccd_active | string }} "
      failed_when: ccd_active
