# Validate test application deployment on K8s
#
# Input: deployment_id
---
- hosts: localhost
  gather_facts: no
  vars:
    namespace: de-cni-test
  roles:
    - get_helm3_path  # Sets helm_path
    - get_kube_config # Sets kubeconfig_path
  tasks:
    - name: Add helm bitnami repo
      kubernetes.core.helm_repository:
        binary_path: "{{ helm_path }}"
        name: bitnami
        repo_url: https://charts.bitnami.com/bitnami
        repo_state: present
      tags:
        - skip_ansible_lint

    - name: Install bitnami/wordpress to {{ namespace }} namespace
      kubernetes.core.helm:
        binary_path: "{{ helm_path }}"
        kubeconfig: "{{ kubeconfig_path }}"
        name: test
        chart_ref: bitnami/wordpress
        namespace: "{{ namespace }}"
        create_namespace: yes
        release_state: present
        wait: yes
        wait_timeout: 20m
        values:
          global: # Use Ericsson docker.io proxy
            imageRegistry: armdocker.rnd.ericsson.se/dockerhub-ericsson-remote
          replicaCount: 3
          persistence:
            enabled: false
          mariadb:
            primary:
              persistence:
                size: 1Gi
      tags:
        - skip_ansible_lint

    - name: Get Wordpress service details
      k8s_info:
        kubeconfig: "{{ kubeconfig_path }}"
        api_version: v1
        kind: Service
        namespace: "{{ namespace }}"
        label_selectors:
          - app.kubernetes.io/name=wordpress
      register: svc

    - name: Get Wordpress external IP
      set_fact:
        wordpress_ip: "{{ svc | json_query('resources[].status.loadBalancer.ingress[].ip') | first }}"

    - name: Check that Wordpress external IP is reachable over http
      uri:
        method: GET
        url: "http://{{ wordpress_ip }}"
        status_code: 200

    - name: Uninstall bitnami/wordpress from {{ namespace }} namespace
      kubernetes.core.helm:
        binary_path: "{{ helm_path }}"
        kubeconfig: "{{ kubeconfig_path }}"
        name: test
        namespace: "{{ namespace }}"
        release_state: absent
      tags:
        - skip_ansible_lint

    - name: Remove {{ namespace }} namespace
      k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        api_version: v1
        kind: Namespace
        name: "{{ namespace }}"
        state: absent

    - name: Remove helm bitnami repo
      kubernetes.core.helm_repository:
        binary_path: "{{ helm_path }}"
        name: bitnami
        repo_url: https://charts.bitnami.com/bitnami
        repo_state: absent
      tags:
        - skip_ansible_lint