---
- name: Get DIT Project Link from DTT Deployments CCD Product
  set_fact:
    dit_project_view_link: "{{ dtt_deployment.products | json_query(products_qry) | first | json_query(links_qry) | first }}"
  vars:
    products_qry: "[? product_type_name == 'CCD'].links"
    links_qry: "[? link_name == 'DIT_Openstack_Project'].url"
- name: Get DIT Project Location from DTT Deployments CCD Product
  set_fact:
    get_dit_project_location: "{{ dtt_deployment.products | json_query(products_qry) | lower }}"
  vars:
    products_qry: "[? product_type_name == 'CCD'].location"
- name: Save DIT Project Location as variable
  set_fact:
    dit_project_location: "{{ get_dit_project_location[0] }}"
- name: Parse Project View link into Project API GET Link
  set_fact:
    dit_project_link: "{{  dit_project_view_link | regex_replace('projects/view', 'api/projects') }}"
- name: Get Project from DIT
  uri:
    method: GET
    url: "{{ dit_project_link }}"
    return_content: yes
    status_code: 200
  register: get_dit_project
  until: get_dit_project.json
  retries: 1
  delay: 3
- name: Save DIT Project as variable
  set_fact:
    dit_project: "{{ get_dit_project.json }}"
- name: Get Projects Cloud from DIT
  uri:
    method: GET
    url: "{{ dit_url }}/api/pods/{{ dit_project.pod_id }}"
    return_content: yes
    status_code: 200
  register: get_dit_pod
  until: get_dit_pod.json
  retries: 1
  delay: 3
- name: Save DIT Project-Cloud as variable
  set_fact:
    dit_pod: "{{ get_dit_pod.json }}"
- name: Save DIT Project-Cloud name as variable
  set_fact:
    dit_pod_name: "{{ dit_pod.name.split('_')| first | regex_replace('Cloud','') }}"
- debug:
    msg: "{{ dit_pod_name }}"
