# Infrastructure
# - Defines the vCenter / vSphere environment
deploy_vsphere_env: 'podb-vcenter_env.yml' # Used to decide on the vcenter_env.yml to fetch from MinIO
deploy_vsphere_cluster: 'POD-B-CCD-Cluster1' # Cluster on which the VMs will be deployed
#deploy_vsphere_resourcepool: 'RP01'

# Guest
# - Describes virtual machine common options
guest_dns_server:
  - '159.107.173.3'
  - '159.107.173.12'
guest_domain_name: 'athtem.eei.ericsson.se'
guest_id: 'sles12_64Guest' #~# NB: DO NOT CHANGE THIS VALUE
