---
- name: Role Requirement, Ensure `jira_ticket` Defined
  assert:
    that:
      - jira_ticket is defined
    fail_msg:
      - "Required vars `jira_ticket` not defined."
      - "Example: CIS-123456"
      - "Exiting playbook!"
    success_msg: "Required var defined."

- name: Close the issue
  jira:
    uri: "{{ jira_module_url }}"
    username: "{{ jira_username }}"
    password: "{{ jira_password }}"
    issue: "{{ jira_ticket }}"
    operation: transition
    status: Closed
  register: close_result

- name: Set the JIRA Close Result
  set_fact:
    jira_close_result: "{{ close_result }}"