#
# Maintainer: Team EE-CNI
# 
# Role to Undefine CAPO cluster configuration for deploymet_id
---
- name: Set ccdadm executable path variable
  set_fact:
    ccdadm_bin: "{{ ccdadm.files[0].path }}"

- name: Undefine CAPO cluster configuration for {{ deployment_id }}
  command: "{{ ccdadm_bin }} cluster undefine -n {{ deployment_id }} --configdir {{ capo_config_path  }}/{{ deployment_id }}/ --debug"
