--- 
- name : Create target.json from Victoria template file for prom.{{ dtt_deployment.name }}.stsoss.{{ dit_project_location }}.gic.ericsson.se for v{{ dit_pod.name | regex_search('POD.*') }}"
  template:
    src: target-victoria.j2
    dest: /tmp/target.json
  when: wiktoria is defined

- name : Create target.json from Prometheus template file for prom.{{ dtt_deployment.name }}.stsoss.{{ dit_project_location }}.gic.ericsson.se for v{{ dit_pod.name | regex_search('POD.*') }}"
  template:
    src: target-promek.j2
    dest: /tmp/target.json
  when: wiktoria is not defined
