---
- name: Query Openstack for ControlPlane VMs
  vars:
    cloud_name: "{{ deployment_env.infra.iaas.capo.clouds.keys() | list | first }}"
    cloud_auth: "{{ deployment_env.infra.iaas.capo.clouds[cloud_name].auth }}"
  environment:
    OS_AUTH_URL: "{{ cloud_auth.auth_url }}"
    OS_PROJECT_ID: "{{ cloud_auth.project_id }}"
    OS_PROJECT_NAME: "{{ cloud_auth.username | replace('_admin','') }}"
    OS_USER_DOMAIN_NAME: "{{ cloud_auth.user_domain_name }}"
    OS_PROJECT_DOMAIN_ID: "{{ cloud_auth.project_domain_name }}"
    OS_USERNAME: "{{ cloud_auth.username }}"
    OS_PASSWORD: "{{ cloud_auth.password }}"
    OS_INTERFACE: public
    OS_IDENTITY_API_VERSION: "{{ cloud_auth.auth_url[-1] }}"
  os_server_info:
    server: '{{ deployment_id }}-controlplane*'
  register: clientvm_info

- name: Create cp_nodes Hosts Group
  add_host:
    group: cp_nodes
    name: "{{ item.name }}"
    ansible_host: "{{ item.ip }}"
    ansible_user: eccd
    ansible_ssh_private_key_file: "{{ pem_location }}"
  loop: "{{ clientvm_info.openstack_servers | json_query(node_query) }}"
  vars:
    node_query: "[*].{name: name, ip: accessIPv4}"