---
- name: Create vip_node Hosts Group
  add_host:
    group: vip_node
    name: "{{ deployment_id }}_controlplane"
    ansible_host: "{{ deployment_vip }}"
    ansible_user: eccd
    ansible_ssh_private_key_file: "{{ pem_location }}"